language: python

services:
  - docker

env:
  global:
    - TEST_RUNNER=esmf-runner
    - DOCKER_IMG=bekozi/esmf-ci
    - PATH=$HOME/.local/bin:$PATH  # for 'aws'

before_install:
  - git clone https://github.com/NESII/esmf-travis-ci.git
  - cd esmf-travis-ci
  - git checkout $TRAVIS_BRANCH
  -
  # 'aws' configuration
#  - pyenv global 3.7.1
#  - pip install -U pip
#  - pip install awscli
#  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
#  - aws s3 sync s3://esmf-test-artifacts/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: Build
      script: exit 0
#        - docker build -q -t $DOCKER_IMG --file docker/esmf-ci/Dockerfile --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
#        - docker run --cpus=$(nproc) -v $(pwd):/esmf-travis-ci -dit --name $TEST_RUNNER $DOCKER_IMG
#        - docker exec -t $TEST_RUNNER bash -c "make info 2>&1 | tee esmf-make-info.out"
#        - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make.sh"
#        - bash sh/travis-finalize-stage.sh
    - stage: Build Unit Tests
      script: exit 0
#        - docker run --cpus=$(nproc) -v $(pwd):/esmf-travis-ci -dit --name $TEST_RUNNER $DOCKER_IMG:$TRAVIS_BRANCH
#        - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make-build_unit_tests.sh"
#        - bash sh/travis-finalize-stage.sh
    - stage: Make Targets #tdk:todo: add summary step that will print failure if a test fails
      script:
        - bash sh/travis-run-make-target-stage.sh "run_unit_tests"
      name: "run_unit_tests"
    - script:
        - bash sh/travis-run-make-target-stage.sh "run_system_tests"
      name: "run_system_tests"
    - script:
        - bash sh/travis-run-make-target-stage.sh "run_examples"
      name: "run_examples"
    - script:
        - docker build -q -t bekozi/esmf-doc:$TRAVIS_BRANCH --file docker/esmf-doc/Dockerfile --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bekozi/esmf-doc:$TRAVIS_BRANCH
      name: "doc"
