language: python

services:
  - docker

env:
  global:
    - TEST_RUNNER=esmf-runner
    - DOCKER_IMG=bekozi/esmf-ci
#  matrix:

before_install:
  - git clone https://github.com/NESII/esmf-travis-ci.git
  - cd esmf-travis-ci
  - docker build -t $DOCKER_IMG --file docker/esmf-ci/Dockerfile --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
  - docker run -dit --name $TEST_RUNNER $DOCKER_IMG

script:
  - echo 'ESMF make info...' && echo -en 'travis_fold:start:esmf_make_info\\r'
  - docker exec -t $TEST_RUNNER bash -c "make info 2>&1 | tee esmf-make-info.out"
  - echo -en 'travis_fold:end:esmf_make_info\\r'

#  - echo 'ESMF make...' && echo -en 'travis_fold:start:esmf_make'
  - travis_wait 30 docker exec -t $TEST_RUNNER bash -c "make > esmf-make.out 2>&1" && tail esmf-make.out
#  - echo -en 'travis_fold:end:esmf_make'

#  - echo 'ESMF make check...' && echo -en 'travis_fold:start:esmf_make_check'
  - travis_wait 30 docker exec -t $TEST_RUNNER bash -c "make check > esmf-make-check.out 2>&1" && tail esmf-make-check.out
#  - echo -en 'travis_fold:end:esmf_make_check'

#  - echo 'ESMF make all_tests...' && echo -en 'travis_fold:start:esmf_make_all_tests'
#  - docker exec -t $TEST_RUNNER bash -c "make all_tests 2>&1 | tee esmf-make-all_tests.out"
#  - echo -en 'travis_fold:end:esmf_make_all_tests'

#  - echo 'ESMF make install...' && echo -en 'travis_fold:start:esmf_make_install'
  - docker exec -t $TEST_RUNNER bash -c "make install > esmf-make-install.out 2>&1" && tail esmf-make-install.out
#  - echo -en 'travis_fold:end:esmf_make_install'

  # ESMPy ---------------------------------------------------------------------

#  - echo 'ESMPy build...' && echo -en 'travis_fold:start:esmpy_build'
  - docker exec -t $TEST_RUNNER bash -c "python setup.py build --ESMFMKFILE=${ESMFMKFILE} > esmpy-build.out 2>&1" && tail esmpy-build.out
#  - echo -en 'travis_fold:end:esmpy_build'

#  - echo 'ESMPy test_all...' && echo -en 'travis_fold:start:esmpy_test_all'
  - docker exec -t $TEST_RUNNER bash -c "python setup.py test_all > esmpy-test_all.out 2>&1" && tail esmpy-test_all.out
#  - echo -en 'travis_fold:end:esmpy_test_all'

#  - echo 'ESMPy install...' && echo -en 'travis_fold:start:esmpy_install'
  - docker exec -t $TEST_RUNNER bash -c "python setup.py install > esmpy-install.out 2>&1" && tail esmpy-install.out
#  - echo -en 'travis_fold:end:esmpy_install'

#  - docker push ...

  # NUOPC Protos --------------------------------------------------------------

#  - docker build -t bekozi/nuopc-protos  --file docker/nuopc-protos/Dockerfile .
