language: python

services:
  - docker

env:
  global:
    - TEST_RUNNER=esmf-runner
    - DOCKER_IMG=bekozi/esmf-ci
#  matrix:

before_install:
  - git clone https://github.com/NESII/esmf-travis-ci.git
  - cd esmf-travis-ci
  - git checkout bekozi-travis-ci #tdk:rm
  - docker build -t $DOCKER_IMG --file docker/esmf-ci/Dockerfile --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
  - docker run -v $(pwd):/esmf-travis-ci -dit --name $TEST_RUNNER $DOCKER_IMG

script:
  - echo 'ESMF make info...' && echo -en 'travis_fold:start:esmf_make_info\\r'
  - docker exec -t $TEST_RUNNER bash -c "make info 2>&1 | tee esmf-make-info.out"
  - echo -en 'travis_fold:end:esmf_make_info\\r'

  - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make.sh"

  - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make-check.sh"

  - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make-install.sh"

#  - echo 'ESMF make...' && echo -en 'travis_fold:start:esmf_make'
#  - travis_wait 30 docker exec -t $TEST_RUNNER bash -c "make > esmf-make.out 2>&1; tail esmf-make.out"
#  - echo -en 'travis_fold:end:esmf_make'

#  - echo 'ESMF make check...' && echo -en 'travis_fold:start:esmf_make_check'
#  - travis_wait 60 docker exec -t $TEST_RUNNER bash -c "make check > esmf-make-check.out 2>&1" && tail esmf-make-check.out
#  - echo -en 'travis_fold:end:esmf_make_check'

#  - echo 'ESMF make all_tests...' && echo -en 'travis_fold:start:esmf_make_all_tests'
#  - docker exec -t $TEST_RUNNER bash -c "make all_tests 2>&1 | tee esmf-make-all_tests.out"
#  - echo -en 'travis_fold:end:esmf_make_all_tests'

#  - echo 'ESMF make install...' && echo -en 'travis_fold:start:esmf_make_install'
#  - docker exec -t $TEST_RUNNER bash -c "make install > esmf-make-install.out 2>&1; tail esmf-make-install.out"
#  - echo -en 'travis_fold:end:esmf_make_install'

  # ESMPy ---------------------------------------------------------------------

#  - echo 'ESMPy build...' && echo -en 'travis_fold:start:esmpy_build'
#  - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmpy-build-test.sh"
#  - echo -en 'travis_fold:end:esmpy_build'

#  - docker push ...

  # NUOPC Protos --------------------------------------------------------------

#  - docker build -t bekozi/nuopc-protos  --file docker/nuopc-protos/Dockerfile .