language: python

services:
  - docker

#env:
#  global:
#  matrix:

before_install:
  - git clone https://github.com/NESII/esmf-travis-ci.git
  - cd esmf-travis-ci
  - git checkout bekozi-exec-for-esmf #tdk:rm

script:
  - docker build -t bekozi/esmf --file docker/esmf/Dockerfile --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
  - docker run -dit --name esmf-runner bekozi/esmf
  - docker exec -t esmf-runner bash -c "make info 2>&1 | tee esmf-make-info.out"
#  - docker build -t bekozi/nuopc-protos  --file docker/nuopc-protos/Dockerfile .
