os:
  - linux
  - osx

language: python

services:
  - docker

env:
  global:
    - TEST_RUNNER=esmf-runner
    - DOCKER_IMG=bekozi/esmf-ci
    - PATH=$HOME/.local/bin:$PATH  # for 'aws'

before_install:
  - git clone https://github.com/NESII/esmf-travis-ci.git
  - cd esmf-travis-ci
  - git checkout $TRAVIS_BRANCH

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda
      source "$HOME/miniconda/etc/profile.d/conda.sh"
      hash -r
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda info -a
    fi

  # 'aws' configuration
#  - pyenv global 3.7.1
#  - pip install -U pip
#  - pip install awscli
#  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
#  - aws s3 sync s3://esmf-test-artifacts/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: Build
      script:
        - exit 0
#        - bash sh/travis/linux/build.sh
    - stage: Build Unit Tests
      script:
        - exit 0
#        - bash sh/travis/linux/build-unit-tests.sh
    - stage: Make Targets #tdk:todo: add summary step that will print failure if a test fails
      script:
        - exit 0
#        - bash sh/travis/linux/run-make-target-stage.sh "run_unit_tests"
      name: "run_unit_tests"
    - script:
        - exit 0
#        - bash sh/travis/linux/run-make-target-stage.sh "run_system_tests"
      name: "run_system_tests"
    - script:
        - exit 0
#        - bash sh/travis/linux/run-make-target-stage.sh "run_examples"
      name: "run_examples"
    - script:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            docker build -t bekozi/esmf-doc:$TRAVIS_BRANCH --file docker/esmf-doc/Dockerfile --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push bekozi/esmf-doc:$TRAVIS_BRANCH > docker-push.out
            tail -n 10 docker-push.out
          else
            echo "Docs built only on linux"
          fi
      name: "doc"
