language: python

services:
  - docker

env:
  global:
    - TEST_RUNNER=esmf-runner
    - DOCKER_IMG=bekozi/esmf-ci
#  matrix:

before_install:
  - git clone https://github.com/NESII/esmf-travis-ci.git
  - cd esmf-travis-ci
  - git checkout $TRAVIS_BRANCH

jobs:
  include:
    - stage: Build
      script:
        - docker build -t $DOCKER_IMG --file docker/esmf-ci/Dockerfile --build-arg ESMF_BRANCH=$TRAVIS_BRANCH .
        - docker run --cpus=$(nproc) -v $(pwd):/esmf-travis-ci -dit --name $TEST_RUNNER $DOCKER_IMG
        - docker exec -t $TEST_RUNNER bash -c "make info 2>&1 | tee esmf-make-info.out"
        - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make.sh"
        - docker commit $TEST_RUNNER $DOCKER_IMG:$TRAVIS_BRANCH
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_IMG:$TRAVIS_BRANCH
        - docker stop $TEST_RUNNER
    - stage: Make Targets
      script:
        - docker run --cpus=$(nproc) -v $(pwd):/esmf-travis-ci -dit --name $TEST_RUNNER $DOCKER_IMG:$TRAVIS_BRANCH
        - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make-check.sh"
        - docker stop $TEST_RUNNER
      name: "check"
    - script: exit 1 #tdk:rm
#    - script: docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmf-make-all_tests.sh"
      name: "all_tests"
    - script: exit 1 #tdk:rm
#    - script: docker build -t bekozi/esmf-ci-doc --file docker/esmf-ci-doc/Dockerfile .
      name: "doc"
#    - stage: Docker Finalize
#      script:
#        - docker commit $TEST_RUNNER bekozi/esmf-ci:latest
#        - docker stop $TEST_RUNNER
#        - docker push #tdk:todo


#  - echo 'ESMF make...' && echo -en 'travis_fold:start:esmf_make'
#  - travis_wait 30 docker exec -t $TEST_RUNNER bash -c "make > esmf-make.out 2>&1; tail esmf-make.out"
#  - echo -en 'travis_fold:end:esmf_make'

#  - echo 'ESMF make check...' && echo -en 'travis_fold:start:esmf_make_check'
#  - travis_wait 60 docker exec -t $TEST_RUNNER bash -c "make check > esmf-make-check.out 2>&1" && tail esmf-make-check.out
#  - echo -en 'travis_fold:end:esmf_make_check'

#  - echo 'ESMF make all_tests...' && echo -en 'travis_fold:start:esmf_make_all_tests'
#  - docker exec -t $TEST_RUNNER bash -c "make all_tests 2>&1 | tee esmf-make-all_tests.out"
#  - echo -en 'travis_fold:end:esmf_make_all_tests'

#  - echo 'ESMF make install...' && echo -en 'travis_fold:start:esmf_make_install'
#  - docker exec -t $TEST_RUNNER bash -c "make install > esmf-make-install.out 2>&1; tail esmf-make-install.out"
#  - echo -en 'travis_fold:end:esmf_make_install'

  # ESMPy ---------------------------------------------------------------------

#  - echo 'ESMPy build...' && echo -en 'travis_fold:start:esmpy_build'
#  - docker exec -t $TEST_RUNNER bash "/esmf-travis-ci/sh/esmpy-build-test.sh"
#  - echo -en 'travis_fold:end:esmpy_build'

#  - docker push ...

  # NUOPC Protos --------------------------------------------------------------

#  - docker build -t bekozi/nuopc-protos  --file docker/nuopc-protos/Dockerfile .